### ISSUE TITLE
Style search filters

### ISSUE THREAD

**Issue by KimSarabia** [Center-for-Research-Libraries/vufind#60]
## Description
Add style to search filters sidebar on search results page
- [ ] General styling improvements to all facet filter components (various derivatives of class facet-group)
- [ ] Make search facets collapsed by default/on load
- [ ] ~Make adjustment in `collection.ini` (line 57?)~ facets.ini
- [ ] Make sure that filter stays uncollapsed if you choose a filter (like in Trinity)

## To-Do
Merge this to #5

**Comment by ryan-jacobs** [comment]
Regarding the collapsible facet filters -- I think this is a nice idea to evaluate and to ensure styling decisions are compatible with. I'm not yet sure if we have an official decision on how to best use this option, but I agree that folks would like to see it in action for further evaluation.

It actually looks like the configuration to adjust is [local/config/vufind/facets.ini](https://github.com/Center-for-Research-Libraries/vufind/blob/crl-dev/local/config/vufind/facets.ini#L163) (we have a "local" copy of this file already as some other options have been customized there in #47). I see that it may even be possible to choose a subset of facets to collapse with something like:

`collapsedFacets = callnumber-first, geographic_facet`

That would collapse the "Classification" and "Geographic Subject". You can get the actual facet IDs from the top of the facets.ini file, or at the and of the id property in the markup. Based on the info that we have to-date it sounds like the "CRL Key Collections" and perhaps the "Year of Publication" groups are important and should be left open... at least as a test case.

**Summary/Suggestion**: Collapse all facets except "CRL Key Collections" and "Year of Publication" so that we have both open/collapsed cases in the prototype and also ensure styling rules are compatible with both open/closed.

**Comment by ryan-jacobs** [comment]
Also, for general styling of the facets, I think the Year of Publication facet filter could use a bit of extra attention. The little slider is nice but the handles look a bit clunky.
